### ISSUE TITLE
安卓闪退

### ISSUE THREAD

**Issue by sofond** [xuqianjin/react-native-aliplayer#10]
你好
安卓集成完进入播放页面闪退，没有看到任何错误信息
苹果下是正常的
安卓在闪退页面多reload几次后，会出现红屏，提示如下信息：

Attempt to invoke interface method 'java.lang.String com.facebook.react.bridge.CatalystInstance.getSourceURL()' on a null object reference

麻烦帮忙看下

环境：
"react": "16.13.1",
"react-native": "0.63.2",

-----------

下载了项目中的Example，跑起来IOS正常，安卓也是闪退...

**Comment by xuqianjin** [comment]
@sofond  看下传值是不是有问题..错误来看是映射出错...

**Comment by sofond** [comment]
> @sofond 看下传值是不是有问题..错误来看是映射出错...

非常感谢您的回复
传的是正常的视频url，没有其它参数
下载了您项目中的Example，跑起来IOS正常，安卓也是闪退...

您跑您仓库中的Example，安卓是正常的嘛？

**Comment by xuqianjin** [comment]
@sofond 是用的真机吗..模拟器会有这个问题..这是阿里sdk的问题
