### ISSUE TITLE
Android 背景颜色或透明的问题

### ISSUE THREAD

**Issue by skyliwq** [xuqianjin/react-native-aliplayer#12]
我在android 设置背景透明 但是不起做用   尝试改动AliSurfaceView   添加  
surfaceView.setZOrderMediaOverlay(true);
surfaceView.getHolder().setFormat(PixelFormat.TRANSLUCENT);

依然无效 请问是否有方法解决 万分感谢

**Comment by xuqianjin** [comment]
播放器背景一般是黑色的。可以看下index.js

**Comment by skyliwq** [comment]
我有一些特别的需求 需要背景透明 可以指点一下需要怎样处理？

**Comment by xuqianjin** [comment]
[https://github.com/xuqianjin/react-native-aliplayer/blob/d8ad42d49f50eddc36a8bd312f497ed7cdea14a5/src/index.js#L13](改下这里试试)

**Comment by xuqianjin** [comment]
[改下这里试试](https://github.com/xuqianjin/react-native-aliplayer/blob/d8ad42d49f50eddc36a8bd312f497ed7cdea14a5/src/index.js#L13)

**Comment by skyliwq** [comment]
就是surfaceView 背景遮挡了底层  我一直没设置明白surfaceView 怎样在透明的情况下还不遮挡其他视图
